name: Unit Tests CI

on:
  push:
       # Rodará em main, develop e em qualquer branch que comece com feature/
       branches:
         - main
         - develop
         - 'feature/**'
       pull_request:
         # Rodará quando um PR for aberto para a branch main
         branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        env:
          # Injeta o token nas variáveis de ambiente do sistema para o Gradle ler
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
        run: ./gradlew testDebugUnitTest